baseline: " A news blog in the Seattle Lower Queen Anne neighborhood."
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: America/Vancouver
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: Lower Queen Anne Post
description: A news blog in the Seattle Lower Queen Anne neighborhood.
baseurl: /
canonicalurl: true
