title: Lower Queen Anne Post
baseline: Your blogging assistant
description: A ready to use static blog, powered by Cecil.
baseurl: /
canonicalurl: true
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: PT
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
